version: '3.8'
services:
  sc-dashboard-backend:
    build: .
    container_name: smartcity-dashboard-backend
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev